base/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_project.urls')),
    path('admin/', admin.site.urls),
]

# local library
urlpatterns += [
    path('oauth/', include('social_django.urls', namespace='social'))
]

main_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from .views import *


urlpatterns = [
    path('', Index.as_view()),
    path('user/add/', RegApp.as_view(), name='user-add'),
    path('home/', TemplateView.as_view(template_name='main_project/home.html'), name='home'),
]

main_project/models.py
from django.db import models

# Create your models here.

main_project/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from django import forms


class FormAddUser(forms.ModelForm):
    """
    Форма для локального добавления
    клиента
    """
    first_name = forms.CharField(widget=forms.TextInput(
                    attrs={
                        'placeholder': 'First Name', 
                        'class': 'form-control' 
                    }))
    last_name = forms.CharField(widget=forms.TextInput(
                    attrs={
                        'placeholder': 'Last Name',
                        'class': 'form-control' 
                    }))
    email = forms.EmailField(required=True, widget=forms.TextInput(
                    attrs={
                        'placeholder': 'Email',
                        'class': 'form-control' 
                    }))
    password = forms.CharField(widget=forms.PasswordInput(
                    attrs={
                        'placeholder': 'Password',
                        'class': 'form-control'
                    }))
    confirm_password = forms.CharField(widget=forms.PasswordInput(
                    attrs={
                        'placeholder': 'Confirm Password',
                        'class': 'form-control'
                    }))
    license_ = forms.BooleanField(
                    help_text='I\'d  like to receive PlacePass news and offers',
                    required=True
                    )
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password',
            'confirm_password'
        )

    def clean_confirm_password(self):
        pswd = self.cleaned_data['confirm_password']
        if pswd != self.cleaned_data.get('password'):
            raise forms.ValidationError('Password not confirmed')
        return pswd

    def clean_license_(self):
        lc = self.cleaned_data['license_']
        if not lc: 
            raise forms.ValidationError('Don\'t enter checkbox like to receive')
        return lc

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError('Email is use')
        return email
        

main_project/views.py
from django.views.generic import FormView, RedirectView

from .forms import FormAddUser


class Index(RedirectView):
    permanent = False
    query_string = True
    pattern_name = 'user-add'

    def get_redirect_url(self, *args, **kwargs):
        return super().get_redirect_url(*args, **kwargs)


class RegApp(FormView):
    form_class = FormAddUser
    template_name = 'main_project/index.html'
    success_url = '/home/'

    def form_valid(self, form):
        from django.contrib.auth import authenticate, login
        email = form.cleaned_data['email']
        form.instance.username = email.split('@')[0]
        form.save()
        user = form.instance
        login(
            self.request,
            user,
            backend='django.contrib.auth.backends.ModelBackend'
        )
        return super(RegApp, self).form_valid(form)

main_project/templates/main_project/base.html
{% extends 'base.html' %}
{% block title %}Test Work{% endblock %}
{% block content %}
    {% block main_content %}{% endblock %}
{% endblock %}

main_project/templates/main_project/home.html
{% extends 'main_project/base.html' %}

{% block main_content %} 
	{% if user.is_authenticated %}
             <p class="display-4">Hello, {{ user.username }}</p>
	{% else %}
             <a class="lead" href="{% url 'user-add' %}">Log in</a>
	{% endif %}
{% endblock %}

main_project/templates/main_project/index.html
{% extends 'main_project/base.html' %}

{% load staticfiles %}

{% block main_content %}  
<div id="addUser">
	<div class="form-border"> 
		<h5 class="text-center">SIGN UP THIS</h5>
		<ul class="social-list">
			<li class="item"><b><a href="{% url 'social:begin' 'facebook' %}">Facebook</a></b></li>
			<li class="marker">/</li>
			<li class="item"><b><a href="{% url 'social:begin' 'google-oauth2' %}">Google</a></b></li>
		</ul>
		<div>
			<div class="liner-text">
				<span>or</span>
			</div>
		</div>
		<form method="post" action="{% url 'user-add' %}" class = "form" role = "form">
		{% csrf_token %}
		{% for field in form %}
			{% if field.name == 'license_' %}
			<div class="mb-2 checkbox">
				{{ field }}
				<label>{{ field.help_text }}</label> 
			</div>
			{% else %}
				<div class="input-group mb-2 {% if field.errors %}has-error{% endif %}" id="group_{{ field.name }}">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon{{ forloop.counter }}">
								{% if field.name == 'first_name' or field.name == 'last_name' %}
									<i class="fa fa-users"></i>
								{% elif  field.name == 'password' or field.name == 'confirm_password' %}
									<i class="fa fa-lock"></i>
								{% else %}
									<i class="fa fa-envelope-o"></i>
								{% endif %}
							</span>
						</div>
					 {{ field }}
				</div>
				 {% if field.errors %}
					{% for error in field.errors %}
					<div class="help-block">
					<small id="{{field.name}}error" class="text-danger">
						{{ error }}
					</small>
					</div>  
					{% endfor %}
				 {% endif %}
			{% endif %}
		{% endfor %}
		<div class="form-group">
			<input type="submit" name="add_data" value="REGISTER" class="btn subm">
		</div>
		</form>
		<div class="flex flex-between">
			<div style="padding-top: 5px;">Aldeady have an account?</div>
			<div><button class="btn btn-outline-info btn-login">LOG IN</button></div>
		</div>
	</div>
</div>
<script>
    $(document).ready(function(){
        manage_button($('#id_license_'));
        $('#id_license_').click(function(){
            manage_button($(this));
        });
        function manage_button(el) {
            if (el.is(':checked')) {
                $('input[type="submit"]').removeAttr("disabled");
            } else {
                $('input[type="submit"]').attr("disabled","disabled");
            }
        }
    });
</script>
{% endblock %}

{% block head_link %}
<link href="{% static 'css/create_user.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4"
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
    {% block head_link %}{% endblock %}
    <style>{% block style %}{% endblock %}</style>
  <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>
<body>
    <div class="conteiner">{% block content %}{%endblock%}</div>
</body>
</html>